[package]
name = "ndjson"
version = "0.1.0"
edition = "2018"

[dependencies]
atty = "0.2"
serde_json = { version = "1.0", features = ["preserve_order"] }
termcolor = "1.1"

[profile.release]
lto = true
